# Generated by Django 4.1.2 on 2023-01-13 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='raxbar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direktor', models.CharField(max_length=45)),
                ('yoordamchisi', models.CharField(max_length=45)),
                ('madanyatchi', models.CharField(max_length=45)),
                ('sekretar', models.CharField(max_length=45)),
            ],
        ),
    ]
