# Generated by Django 4.1.2 on 2023-01-14 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myfiles', '0003_news'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sharoyit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rasim', models.ImageField(upload_to='media')),
                ('name', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Talim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rasim', models.ImageField(upload_to='media')),
                ('name', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=500)),
            ],
        ),
    ]
