# Generated by Django 4.1.2 on 2023-01-14 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myfiles', '0005_rename_name_sharoyit_names_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Murojat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fish', models.CharField(max_length=100)),
                ('otasi', models.CharField(max_length=100)),
                ('onasi', models.CharField(max_length=100)),
                ('rasim', models.ImageField(upload_to='media')),
                ('malumot', models.TextField()),
                ('raqam', models.CharField(max_length=12)),
                ('vaqt', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
