# Generated by Django 4.1.2 on 2023-01-14 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myfiles', '0009_alter_murojat_rasim'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Murojat',
        ),
    ]
