# Generated by Django 4.1.2 on 2023-01-14 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myfiles', '0010_delete_murojat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='rasim',
            field=models.ImageField(upload_to='media'),
        ),
        migrations.AlterField(
            model_name='sharoyit',
            name='rasims',
            field=models.ImageField(upload_to='media'),
        ),
        migrations.AlterField(
            model_name='talim',
            name='rasimt',
            field=models.ImageField(upload_to='media'),
        ),
    ]
