# Generated by Django 4.1.4 on 2023-01-17 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myfiles', '0012_murojat'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dasturchi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nnn', models.CharField(max_length=200, verbose_name='Ismi: ')),
                ('rrr', models.ImageField(upload_to='media/photo', verbose_name='Rasmi: ')),
                ('ttt', models.CharField(max_length=12, verbose_name='Telefon raqami: ')),
                ('smm', models.CharField(max_length=200, verbose_name='Telegram: ')),
                ('about', models.CharField(max_length=500, verbose_name="Qo'shimcha ma'lumotlar: ")),
            ],
        ),
    ]
