# Generated by Django 4.1.4 on 2023-01-18 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myfiles', '0014_alter_news_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Xodimlar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ismit', models.CharField(max_length=80, verbose_name='Ismi va Familiyasi')),
                ('rasmit', models.ImageField(upload_to='media/xodimlar', verbose_name='Rasmi')),
                ('yoshi', models.BigIntegerField(verbose_name='Yoshi')),
                ('fan', models.CharField(max_length=40, null=True, verbose_name='Fani')),
                ('lavozimi', models.CharField(max_length=90, verbose_name='Lavozimi')),
            ],
        ),
    ]
