# Generated by Django 4.1.4 on 2023-01-18 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myfiles', '0016_xodimlar_about_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='xodimlar',
            name='tel_raqam',
            field=models.CharField(default=1, max_length=20, verbose_name='Telefon raqami'),
            preserve_default=False,
        ),
    ]
